### ISSUE TITLE
Website not updating

### ISSUE THREAD

**Issue by bawee** [food-safety-bioinformatics-hackathon/AMR-workflows#11]
Hi Will,
How often does the website take to update the layouts that we've committed? It's been showing the old content for a while now. 

Did i break it? I tried adding hierarchical categories to the Database and Pseudomonas post. 

Cheers,
Bryan

**Comment by will-rowe** [comment]
yep - looks like it was because the new hierarchy, jekyll doesn't now how to handle it

**Comment by will-rowe** [comment]
We should probably add a build test - I hadn't had time yet! Just adding markdown content via a post which uses our template shouldn't break anything. Changes to metadata tags etc. will need checking and some tinkering with the site.

You can try running `jekyll serve --watch` in the /doc directory before committing changes to the site, that will show any errors in the build.

**Comment by bawee** [comment]
Thanks, Will!

**Comment by will-rowe** [comment]
Shall I fix this or are you reverting your changes?

**Comment by bawee** [comment]
I've reverted. It's back online now
